title: angelos.work
email: aperivol@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Portfolio page
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.angelos.work" # the base hostname & protocol for your site
logo: '/assets/images/favicon.png'
# twitter_username: jekyllrb
# github_username:  jekyll

include: ["_pages"]

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Minimal Mistakes theme settings
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "plain", "sunrise", "default"
show_excerpts: true # set to false to remove excerpts on the homepage

# Pagination settings
paginate: 5 # amount of posts to show
paginate_path: "/page:num/"

# SEO settings
author: Angelos Perivolaropoulos
# twitter:
#   username: yourhandle
#   card: summary
# seo:
#   type: WebPage
#   image:
#     path: /assets/images/seo-image.jpg
#     height: 1000
#     width: 1000

# Google Analytics and other scripts
# google_analytics: UA-123456789-1
# footer:
#   links:
#     - label: "Twitter"
#       icon: "fab fa-fw fa-twitter-square"
#       url: "https://twitter.com/yourhandle"
#     - label: "GitHub"
#       icon: "fab fa-fw fa-github"
#       url: "https://github.com/yourhandle"

# Exclude from production build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
